default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taganrog_map_development
test:
  <<: *default
  database: taganrog_map_test
production:
  <<: *default
  database: taganrog_map_production
  username: taganrog_map
  password: <%= ENV["TAGANROG_MAP_DATABASE_PASSWORD"] %>
